export const usersData: any[] = [
    {
      id: 1,
      picture: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541",
      name: "John Doe",
      email: "johndoe@example.com",
      phone: "123-456-7890",
      date_of_birth: "1990-01-15",
      gender: "Male",
      nationality: "American",
      marital_status: "Single",
      linkedin: "https://linkedin.com/in/johndoe",
      github: "https://github.com/johndoe",
      portfolio: "https://johndoe.dev",
      position: "Software Engineer",
      department: "Development",
      start_date: "2020-06-01",
      end_date: "Present",
      responsibilities: "Developing and maintaining software applications.",
      salary_type: "Monthly",
      rate: "$6000",
      benefits: "Health Insurance, Stock Options",
      contract_type: "Full-time",
    },
    {
      id: 2,
      picture: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541",
      name: "Jane Smith",
      email: "janesmith@example.com",
      phone: "987-654-3210",
      date_of_birth: "1992-07-22",
      gender: "Female",
      nationality: "British",
      marital_status: "Married",
      linkedin: "https://linkedin.com/in/janesmith",
      github: "https://github.com/janesmith",
      portfolio: "https://janesmith.dev",
      position: "Project Manager",
      department: "Operations",
      start_date: "2018-03-10",
      end_date: "Present",
      responsibilities: "Overseeing project timelines and deliverables.",
      salary_type: "Monthly",
      rate: "$7000",
      benefits: "Bonus, Paid Vacation",
      contract_type: "Full-time",
    },
    {
      id: 3,
      picture: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541",
      name: "Michael Brown",
      email: "michaelbrown@example.com",
      phone: "456-789-0123",
      date_of_birth: "1988-11-05",
      gender: "Male",
      nationality: "Canadian",
      marital_status: "Single",
      linkedin: "https://linkedin.com/in/michaelbrown",
      github: "https://github.com/michaelbrown",
      portfolio: "https://michaelbrown.dev",
      position: "UI/UX Designer",
      department: "Design",
      start_date: "2019-09-15",
      end_date: "Present",
      responsibilities: "Designing user-friendly interfaces and experiences.",
      salary_type: "Monthly",
      rate: "$5500",
      benefits: "Flexible Work Hours, Gym Membership",
      contract_type: "Full-time",
    },
    {
      id: 4,
      picture: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541",
      name: "Emily White",
      email: "emilywhite@example.com",
      phone: "321-654-0987",
      date_of_birth: "1995-03-30",
      gender: "Female",
      nationality: "Australian",
      marital_status: "Engaged",
      linkedin: "https://linkedin.com/in/emilywhite",
      github: "https://github.com/emilywhite",
      portfolio: "https://emilywhite.dev",
      position: "Data Analyst",
      department: "Business Intelligence",
      start_date: "2021-01-05",
      end_date: "Present",
      responsibilities: "Analyzing business data for insights and improvements.",
      salary_type: "Monthly",
      rate: "$5000",
      benefits: "Remote Work, Learning Stipend",
      contract_type: "Full-time",
    },
    {
      id: 5,
      picture: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png?20150327203541",
      name: "David Johnson",
      email: "davidjohnson@example.com",
      phone: "789-012-3456",
      date_of_birth: "1985-06-18",
      gender: "Male",
      nationality: "German",
      marital_status: "Divorced",
      linkedin: "https://linkedin.com/in/davidjohnson",
      github: "https://github.com/davidjohnson",
      portfolio: "https://davidjohnson.dev",
      position: "Cybersecurity Specialist",
      department: "IT Security",
      start_date: "2017-08-25",
      end_date: "Present",
      responsibilities: "Protecting company data from cyber threats.",
      salary_type: "Monthly",
      rate: "$7500",
      benefits: "Company Car, Pension Plan",
      contract_type: "Full-time",
    }
  ];
  